export const PROFIT_MARGIN = 0
export const REQUEST_CREDIT_SHOW_THRESHOLD = 0
export const MAX_DATE = new Date(86399999999999)
export const BILLING_PERIOD_DAYS = 30
export const SESSION_MAX_AGE_SECONDS = 30 * 24 * 60 * 60
export const SESSION_TIME_WINDOW_MS = 30 * 60 * 1000
export const CREDITS_REFERRAL_BONUS = 0
export const AFFILIATE_USER_REFFERAL_LIMIT = 0
export const DEFAULT_FREE_CREDITS_GRANT = 1000000
export const CREDIT_PRICING = {
  CENTS_PER_CREDIT: 0,
  MIN_PURCHASE_CREDITS: 0,
  DISPLAY_RATE: 'Free',
} as const
